# Generated by Django 2.1.2 on 2018-11-20 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascotas',
            name='foto',
            field=models.ImageField(upload_to='mascotas', verbose_name='Foto Mascota'),
        ),
    ]
